spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 111111
    url: jdbc:mysql://127.0.0.1:3306/shop?useUnicode=true&characterEncoding=UTF8&useSSL=false&serverTimezone=UTC&transformedBitIsBoolean=true&allowMultiQueries=true
  jpa:
    show-sql: true
  freemarker:
    template-loader-path: classpath:/templates  # classpath:  一定不能漏写
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    suffix: .ftl
#  resources:
#    static-locations: classpath:/static/
  redis:
    host: 10.10.10.216
    client-name: test
    password: 111111

#  //配置json返回对象不为空
#  jackson:
#    default-property-inclusion: non_null
server:
  servlet:
    context-path: /sell
  port: 8083
#logging:
#  pattern:
#    console: "%d - %msg%n"
projectUrlConfig:
  sell: 127.0.0.1:8083

#mybatis 配置mapper路径（可配置多个）
mybatis:
  mapper-locations: classpath:mapper/*.xml
